# opadev2-team
web:
  okta-sso_settings:
    com.optum.mstrweb.sso.okta.clientid: '0oamh6hlhtnjjZGuK0h7'

  okta_esm_settings:
    com.optum.mstrweb.sso.okta.esm.jdbc.url: 'jdbc:redshift://opadevredshift-1-redshift-cluster.clxtymtfekvn.us-east-1.redshift.amazonaws.com:5439/deid_qa'

  client_users_group_guid_to_users_folder_lookup: 
    D89C39C811E9AF0C00000080EF3597A9: 
      ClientUsersFolderName: "Mock Users"
    133AC8E748BB64E4A2F16794F604E656: 
      ClientUsersFolderName: "NYU Users"
    6366A61446F9662C83E0DFA24D08E8FC: 
      ClientUsersFolderName: "Populytics Users"
    0BEC4B3C11E886CE01AF0080EFF57A32: 
      ClientUsersFolderName: "Blue Cross NC Users"
    720132BC4A192165D4CBC380D7A797B9: 
      ClientUsersFolderName: "Demo Users"
    2B9F4060422FEB1415AF3F8A876D84DA: 
      ClientUsersFolderName: "Training Users"

  custom_alert_message:
    StartDateTime: "12/18/2018 17:00:00"
    EndDateTime: "12/31/2018 20:00:00"