# opa-prod-mstr-enterprise-4
# OhioHealth
web:
  okta-sso_settings:
    com.optum.mstrweb.sso.okta.clientid: "0oabv706mid6GyZvy1t7"

  client_users_group_guid_to_users_folder_lookup:
    FE6E594611E9E12100000080EFE5477D: 
      ClientUsersFolderName: "OhioHealth Users"

  custom_alert_message:
    StartDateTime: "12/18/2018 17:00:00"
    EndDateTime: "12/31/2018 20:00:00"