web:
  okta-sso_settings:
    com.optum.mstrweb.sso.okta.clientid: "0oabz6t0xwihpv4bs1t7"
    com.optum.mstrweb.sso.okta.oktadiscoveryurl: "https://onelogin.advisory.com/oauth2/aus4blhnknOySLli21t7/.well-known/openid-configuration"
    com.optum.mstrweb.sso.okta.configparam.idp: "0oac7jksa8hudZZ071t7"

  client_users_group_guid_to_users_folder_lookup:
    94300BDE11E97E7400000080EFE5222A:
      ClientUsersFolderName: "Mercy Users"

  custom_alert_message:
    StartDateTime: "12/18/2018 17:00:00"
    EndDateTime: "12/31/2018 20:00:00"
