web:
  okta-sso_settings:
    com.optum.mstrweb.sso.okta.clientid: "0oacawkodhQ9y7rRh1t7"

  client_users_group_guid_to_users_folder_lookup:
    35CD0DC811E9FF1900000080EFC5C5D2:
      ClientUsersFolderName: "Wilmington Users"

  custom_alert_message:
    StartDateTime: "12/18/2018 17:00:00"
    EndDateTime: "12/31/2018 20:00:00"
