web:
  okta-sso_settings:
    com.optum.mstrweb.sso.okta.clientid: "0oac76elwlA07zZwz1t7"

  client_users_group_guid_to_users_folder_lookup:
    F6FA7F0211EA001400000080EF956483:
      ClientUsersFolderName: "UMass Users"

  custom_alert_message:
    StartDateTime: "12/18/2018 17:00:00"
    EndDateTime: "12/31/2018 20:00:00"
